name: fourseven_oneseven

services:
  nginx:
    image: nginx:alpine
    networks:
      - web_network
    depends_on:
      - jobify
      - pixify
      - frontend
    volumes:
      - ../scripts:/docker-entrypoint.d/scripts:ro

  frontend:
    environment:
      - VITE_AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - VITE_AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
      - VITE_AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
    build:
      context: ../../fourseven_oneseven_frontend
    networks:
      - web_network

  jobify:
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - FLASK_APP=src
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
      - AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5004/api/status"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 60s
    build:
      context: ../../jobify
    networks:
      - web_network
    expose:
      - "5004"

  pixify:
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - FLASK_APP=src
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
      - AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5005/api/status"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 60s
    build:
      context: ../../pixify
    networks:
      - web_network
    expose:
      - "5005"

networks:
  web_network:
    driver: bridge
