name: fourseven_oneseven

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    networks:
      - web_network
    depends_on:
      - jobify
      - pixify
      - frontend

  frontend:
    build:
      context: ../../fourseven_oneseven_frontend
    volumes:
      - ../../fourseven_oneseven_frontend:/app
      - /app/node_modules
    networks:
      - web_network

  jobify:
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5004/api/status"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 60s
    build:
      context: ../../jobify
    networks:
      - web_network
    expose:
      - "5004"
    ports:
      - "5004:5004"
    volumes:
      - ../../jobify/src:/app/src

  pixify:
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5005/api/status"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 60s
    build:
      context: ../../pixify
    networks:
      - web_network
    expose:
      - "5005"
    ports:
      - "5005:5005"
    volumes:
      - ../../pixify/src:/app/src

networks:
  web_network:
    driver: bridge
