name: fourseven_oneseven

services:
  nginx:
    volumes:
      - ../nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro

  frontend:
    build:
      target: development
    environment:
      - NODE_ENV=development
    volumes:
      - ../../fourseven_oneseven:/app
      - /app/node_modules
    command: npm run dev

  jobify:
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
      - FLASK_APP=src
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    volumes:
      - ../../jobify/src:/app/src

  pixify:
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
      - FLASK_APP=src
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    volumes:
      - ../../pixify/src:/app/src
