name: fourseven_oneseven

services:
  nginx:
    volumes:
      - ../nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro

  frontend:
    ports:
      - "5174:5174"
    build:
      target: development
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    command: npm run dev

  jobify:
    environment:
      - FLASK_APP=src
      - FLASK_ENV=development
      - FLASK_DEBUG=1

  pixify:
    environment:
      - FLASK_APP=src
      - FLASK_ENV=development
      - FLASK_DEBUG=1
