name: fourseven_oneseven

services:
  nginx:
    ports:
      - "80:80"
    volumes:
      - ../nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro

  frontend:
    ports:
      - "5174:5174" # There's a port conflict with Docker
    build:
      target: development
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    command: npm run dev
    volumes:
      - /app/node_modules
      - ../../fourseven_oneseven_frontend/src:/app/src
      - ../../fourseven_oneseven_frontend/public:/app/public
      - ../../fourseven_oneseven_frontend/package.json:/app/package.json

  jobify:
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    ports:
      - "5004:5004"
    volumes:
      - ../../jobify/src:/app/src

  pixify:
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    ports:
      - "5005:5005"
    volumes:
      - ../../pixify/src:/app/src
