#!/usr/bin/env python3
"""Turn ha_metrics.toml into idempotent seed SQL for metric_catalog and
metric_grain_period.

Validates what a database constraint cannot express: that a metric's grain
periods are CONTIGUOUS. The exclusion constraint catches overlaps; only this
catches a hole between two ranges, which would leave timestamps in the gap
resolving to no grain at all.

Usage:  python3 gen_seed.py > seed_catalog.sql
"""
import sys
import tomllib
from pathlib import Path

SRC = Path(__file__).parent / "ha_metrics.toml"


def sql_str(v):
    if v is None or v is False:
        return "NULL"
    return "'" + str(v).replace("'", "''") + "'"


def sql_num(v):
    return "NULL" if v is None or v is False else str(v)


def sql_bool(v):
    return "true" if v else "false"


def validate_grain_periods(periods):
    """Exhaustive-coverage check, per statistic_id.

    Adjacency alone is not enough. A lone bounded period, a first period that
    starts after -infinity, or a final bounded period each pass an adjacency
    check while still leaving timestamps that resolve to no grain at all --
    which the sync treats as a hard error. If a metric overrides grain, its
    ranges must cover the whole timeline.
    """
    by_metric = {}
    for p in periods:
        by_metric.setdefault(p["statistic_id"], []).append(p)

    for sid, ps in by_metric.items():
        ps.sort(key=lambda p: str(p["valid_from"]))

        if str(ps[0]["valid_from"]) != "-infinity":
            sys.exit(f"ERROR: {sid}: first grain period starts at "
                     f"{ps[0]['valid_from']}, leaving all earlier timestamps "
                     f"unresolved. It must start at -infinity.")

        if ps[-1].get("valid_until") not in (None, False):
            sys.exit(f"ERROR: {sid}: final grain period ends at "
                     f"{ps[-1]['valid_until']}, leaving all later timestamps "
                     f"unresolved. It must be open-ended (valid_until = false).")

        for a, b in zip(ps, ps[1:]):
            if a.get("valid_until") in (None, False):
                sys.exit(f"ERROR: {sid}: open-ended period at {a['valid_from']} "
                         f"is followed by another period at {b['valid_from']}")
            if str(a["valid_until"]) != str(b["valid_from"]):
                kind = ("gap" if str(a["valid_until"]) < str(b["valid_from"])
                        else "overlap")
                sys.exit(f"ERROR: {sid}: {kind} at boundary "
                         f"{a['valid_until']} -> {b['valid_from']} - periods "
                         f"must be exactly contiguous")
        sys.stderr.write(f"[seed] {sid}: {len(ps)} contiguous grain periods\n")


def main():
    doc = tomllib.loads(SRC.read_text())
    metrics = doc["metric"]
    periods = doc.get("grain_period", [])
    validate_grain_periods(periods)

    out = ["-- GENERATED by gen_seed.py from ha_metrics.toml - do not edit.",
           "-- Re-run the generator and re-apply instead.",
           "",
           "BEGIN;",
           ""]

    for m in metrics:
        out.append(
            "INSERT INTO homeassistant.metric_catalog (statistic_id, category, "
            "display_name, source, unit_of_measurement, unit_class, mean_type, "
            "has_sum, energy_role, max_plausible_kw, default_grain, is_active) VALUES ("
            f"{sql_str(m['statistic_id'])}, {sql_str(m['category'])}, "
            f"{sql_str(m['display_name'])}, {sql_str(m['source'])}, "
            f"{sql_str(m.get('unit_of_measurement'))}, {sql_str(m.get('unit_class'))}, "
            f"{sql_num(m.get('mean_type'))}, {sql_bool(m.get('has_sum'))}, "
            f"{sql_str(m.get('energy_role'))}, {sql_num(m.get('max_plausible_kw'))}, "
            f"{sql_str(m.get('default_grain', 'hour'))}, "
            f"{sql_bool(m.get('is_active', True))})")
        out.append(
            "ON CONFLICT (statistic_id) DO UPDATE SET "
            "category = EXCLUDED.category, display_name = EXCLUDED.display_name, "
            "source = EXCLUDED.source, unit_of_measurement = EXCLUDED.unit_of_measurement, "
            "unit_class = EXCLUDED.unit_class, mean_type = EXCLUDED.mean_type, "
            "has_sum = EXCLUDED.has_sum, energy_role = EXCLUDED.energy_role, "
            "max_plausible_kw = EXCLUDED.max_plausible_kw, "
            "default_grain = EXCLUDED.default_grain, is_active = EXCLUDED.is_active;")
        out.append("")

    # Replace grain periods wholesale: a changed boundary must not leave the
    # old range behind, and the exclusion constraint would reject the overlap.
    if periods:
        sids = ", ".join(sorted({sql_str(p["statistic_id"]) for p in periods}))
        out.append(f"DELETE FROM homeassistant.metric_grain_period "
                   f"WHERE statistic_id IN ({sids});")
        out.append("")
        for p in periods:
            vu = p.get("valid_until")
            out.append(
                "INSERT INTO homeassistant.metric_grain_period "
                "(statistic_id, valid_from, valid_until, grain) VALUES ("
                f"{sql_str(p['statistic_id'])}, {sql_str(p['valid_from'])}::timestamptz, "
                f"{sql_str(vu)}{'::timestamptz' if vu not in (None, False) else ''}, "
                f"{sql_str(p['grain'])});")
        out.append("")

    out.append("COMMIT;")
    print("\n".join(out))
    sys.stderr.write(f"[seed] {len(metrics)} metrics, {len(periods)} grain periods\n")


if __name__ == "__main__":
    main()
